### ISSUE TITLE
Possibly show ECC ElGamal to demonstrate mapping message to a group element

### ISSUE THREAD

**Issue by mundungus443** [johndoe31415/toyecc#2]
I think it would be helpful to illustrate ECC ElGamal, especially to show the process of mapping an arbitrary message integer onto an element of the ECC group.

**Comment by johndoe31415** [comment]
Hi there, if my understanding is correct then the mapping that is usually used for ElGamal is that for a given integer i, the point (i, y) is chosen. This means you would insert i as the x value into the curve equation, get your y^2 value and calculate the "square root" of that to get your y coordinate. I think that there's even a function already that gives you a point of the curve when you have the x coordinate. Note that this only works when your y^2 value is a quadratic residue in the chosen field -- if it isn't I'm not sure how ElGamal works in that scenario (just keep choosing other random i values until you find a QR mod p?).

Would you want to submit a PR for this change?

**Comment by johndoe31415** [comment]
Hey there -- so I've given it a shot; it's a separate file called elgamaltest.py in the root directory. Regarding performance, is this as terrible as the result you're getting? Then it just might be that it's terribly slow (it's a pure Python implementation, not meant for great performance). Let me know your comments and, if this fixes your issue, feel free to close this ticket. Thanks!

**Comment by ThePlasmaRailgun** [comment]
Sorry it's taken so long to get back to you. 100 trials is definitely not enough to perform reliable ElGamal mapping. Additionally, you probably want to use the loop variable as the lower bits so it isn't jumping as much with each increment. From what I've read, you want at least around 32 bytes of room to increment to attempt to find such an x value. 
That's where splitting a 4000 byte or so random message into 16 byte blocks and encrypting each is useful for testing. That means that you have a LOT more random trials than just something like foobar, which may map fine, while something like barfoo123 may actually fail to map with only 100 trials

**Comment by ThePlasmaRailgun** [comment]
This is my current ElGamal class:

```
class ElGamal:
    def __init__(self, curve: EllipticCurve):
        assert curve.hasgenerator
        self.curve = curve

    def _encrypt_point(self, message: AffineCurvePoint, public_key: ECPublicKey):
        assert self.curve.on_curve(message)
        assert public_key.curve == self.curve
        assert self.curve.on_curve(public_key.point)

        r = random.randint(1, self.curve.n - self.curve.n // 2)

        return self.curve.g * r, message + (public_key.point * r)

    def _decrypt_point(self, c1: AffineCurvePoint, c2: AffineCurvePoint, private_key: ECPrivateKey):
        assert self.curve.on_curve(c1) and self.curve.on_curve(c2)
        assert private_key.curve == self.curve

        return c2 + self.curve.point_conjugate(c1 * private_key.scalar)

    def encrypt(self, message: int, public_key: ECPublicKey, blocksize=32):
        message_size = blocksize * 8
        curve_size = self.curve.curve_order.bit_length()

        k = curve_size - message_size

        m = message << k

        point = None

        for i in range(k ** 2):
            y = self.curve.value_at(m)
            if y is not None:
                point = AffineCurvePoint(m, int(y), self.curve)
                break
            m += 1
        if point is None:
            raise ValueError
        return self._encrypt_point(point, public_key)

    def decrypt(self, c1: AffineCurvePoint, c2: AffineCurvePoint, private_key: ECPrivateKey, blocksize=32):
        message_size = blocksize * 8
        curve_size = self.curve.curve_order.bit_length()

        k = curve_size - message_size

        decrypted = self._decrypt_point(c1, c2, private_key)

return int(decrypted.x) >> k
```

**Comment by johndoe31415** [comment]
I disagree with your rationale, here's why:

Let's take secp521r1 as an example. #E(F_p) is roughly 6.865e156. Note that the finite field's size is almost exactly that (the trace of the curve is a 259-bit integer, i.e., *tiny* compared to the huge 521 bit field). Since the curve is symmetric and assuming that points are distributed randomly, we therefore have roughly a 50% chance of finding a point pair for every randomly chosen X coordinate. This means that for no success to occur after 100 trials, the probability would be about 0.5^100 = 7.89e-31. IOW it is about 33 times likelier to win the German lottery (1 / nCr(49, 6)) four times consecutively than for 100 consecutive point finding trials to fail.

For curves in which the trace is comparatively small, the cofactor therefore is the only thing to consider here and the probability to find a point would be p = 1 / 2h for each trial. For a cofactor 8 curve, that means that failure after 100 trials would still have a residual probability of about p = 0.002. I.e., for such a curve, increasing the trial count may be advisable -- then again, it's meant to only showcase the ideas around algorithms around elliptic curves and I really don't expect anyone to seriously use this for production purposes.

I find it highly unlikely that anyone would need 32 bytes of room to increment necessary. That stems from the fact that even if the mere incrementing action would only take Planck time, it would still take 1.98e26 years. For comparison, that is far far far beyond the time at which our sun will have burnt up. My gut feeling says that 32 bits should be way enough, especially considering that if your curve is so broken that you need around 4 billion trials to find a valid point, it's probably a very bad choice for ElGamal.

As to the lower/upper portion of the X coordinate to be used for the mapping, I don't see why either one would have an advantage over the other apart from mere preference. Can you elaborate why you believe that the changing points pose an issue?
